# Generated by Django 4.2.3 on 2023-07-23 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='image_url',
            field=models.CharField(default='https://res.cloudinary.com/dagfqp7qa/image/upload/v1688892172/samples/cloudinary-icon.png', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='expoPushToken',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='errand.itemreview')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='errand.listitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
