# Generated by Django 4.2.3 on 2023-07-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0002_user_expopushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='image_url',
            field=models.CharField(default='https://res.cloudinary.com/dagfqp7qa/image/upload/v1688892172/samples/cloudinary-icon.png', max_length=500),
        ),
    ]
