# Generated by Django 4.2.3 on 2023-07-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0002_listitem_image_url_user_expopushtoken_reviewreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expoPushToken',
        ),
    ]
