# Generated by Django 4.2.3 on 2023-07-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0004_listitem_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='job_status',
        ),
        migrations.AddField(
            model_name='listitem',
            name='task_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
