# Generated by Django 4.2.3 on 2023-07-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0006_taskrequests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskRequests',
        ),
    ]
