# Generated by Django 4.2.3 on 2023-07-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0009_remove_request_status_request_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_status',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
