# Generated by Django 4.2.3 on 2023-07-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0010_remove_request_request_status_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
    ]
